apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: growth-core-secret
  namespace: statex-apps
  labels:
    app: growth-core
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: growth-core-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: secret/prod/growth-core
        property: DB_PASSWORD
