apiVersion: v1
kind: Service
metadata:
  name: growth-core
  namespace: statex-apps
  labels:
    app: growth-core
    managed-by: k8s-migration
spec:
  type: ClusterIP
  selector:
    app: growth-core
  ports:
    - protocol: TCP
      port: 3376
      targetPort: 3376
      name: http
